[package]
name = "consumer_duck"
version = "0.1.0"
edition = "2021"
[workspace]
[lib]
name = "consumer"
path = "src/lib.rs"
[[bin]]
name = "consumer-bin"
path = "src/main.rs"

[profile.dev]
debug = "line-tables-only"

[profile.release]
lto = "thin"
strip = true

[dependencies]
duckdb = { version = "=1.10504.0", features = ["bundled", "parquet", "json"] }
