#!/usr/bin/env python3
"""Copy DefaultPhysicalPlanner out of the datafusion 55.0.0 umbrella crate and
rewrite its `crate::` imports so it builds against the component crates.

The COPY arm is stubbed: it is the only path that needs umbrella-only file-sink
helpers, and the admitted subset does not COPY.
"""
from __future__ import annotations

import glob
import os
import sys

REGISTRY = os.path.expanduser("~/.cargo/registry/src")
SRC = glob.glob(os.path.join(REGISTRY, "*", "datafusion-55.0.0", "src", "physical_planner.rs"))
EQ = glob.glob(os.path.join(REGISTRY, "*", "datafusion-55.0.0", "src", "schema_equivalence.rs"))
if not SRC or not EQ:
    sys.exit(f"datafusion-55.0.0 not in cargo registry ({REGISTRY})")
SRC, EQ = SRC[0], EQ[0]

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "components", "src", "generated")
os.makedirs(OUT, exist_ok=True)


def take_until_tests(path: str) -> str:
    lines = []
    with open(path) as f:
        for line in f:
            if line.startswith("#[cfg(test)]"):
                break
            lines.append(line)
    return "".join(lines)


def stub_copy_arm(text: str) -> str:
    needle = "            LogicalPlan::Copy(CopyTo {"
    start = text.find(needle)
    if start < 0:
        sys.exit("Copy arm not found")
    next_arm = text.find("            LogicalPlan::Dml(DmlStatement {", start)
    if next_arm < 0:
        sys.exit("Dml arm after Copy not found")
    stub = (
        "            LogicalPlan::Copy(_) => {\n"
        '                return not_impl_err!("COPY is not part of the admitted subset");\n'
        "            }\n"
    )
    return text[:start] + stub + text[next_arm:]


IMPORT_REWRITES = [
    (
        "use crate::datasource::file_format::file_type_to_format;\n",
        "",
    ),
    (
        "use crate::datasource::listing::ListingTableUrl;\n",
        "",
    ),
    (
        "use crate::datasource::physical_plan::{FileOutputMode, FileSinkConfig};\n",
        "",
    ),
    (
        "use crate::datasource::{DefaultTableSource, source_as_provider};\n",
        "use datafusion_catalog::default_table_source::{DefaultTableSource, source_as_provider};\n",
    ),
    (
        "use crate::error::{DataFusionError, Result};\n",
        "use datafusion_common::{DataFusionError, Result};\n",
    ),
    (
        "use crate::execution::context::ExecutionProps;\n",
        "use datafusion_expr::execution_props::ExecutionProps;\n",
    ),
    (
        "use crate::logical_expr::utils::generate_sort_key;\n",
        "use datafusion_expr::utils::generate_sort_key;\n",
    ),
    ("use crate::logical_expr::", "use datafusion_expr::"),
    ("use crate::physical_expr::", "use datafusion_physical_expr::"),
    ("use crate::physical_plan::", "use datafusion_physical_plan::"),
    (
        "use crate::schema_equivalence::schema_satisfied_by;\n",
        "use crate::schema_equivalence::schema_satisfied_by;\n",
    ),
]


def rewrite_planner(text: str) -> str:
    text = stub_copy_arm(text)
    for old, new in IMPORT_REWRITES:
        text = text.replace(old, new)
    leftover = [ln for ln in text.splitlines() if "crate::" in ln and "schema_equivalence" not in ln and "config::ExecutionOptions" not in ln]
    header = (
        "// Generated by rewrite_planner.py from datafusion-55.0.0. Do not edit.\n"
        "#![allow(unused_imports, dead_code, unused_variables, clippy::all)]\n"
    )
    if leftover:
        header += "// leftover crate:: refs (compile will say):\n"
        for ln in leftover[:20]:
            header += f"// {ln.strip()}\n"
    return header + text


planner = rewrite_planner(take_until_tests(SRC))
eq = take_until_tests(EQ).replace("pub(crate) fn schema_satisfied_by", "pub fn schema_satisfied_by")
eq = "// Generated by rewrite_planner.py from datafusion-55.0.0. Do not edit.\n" + eq

open(os.path.join(OUT, "physical_planner.rs"), "w").write(planner)
open(os.path.join(OUT, "schema_equivalence.rs"), "w").write(eq)
print(f"wrote {OUT} ({planner.count(chr(10))} planner lines)")
