//! `src/df/generated/{physical_planner,schema_equivalence}.rs` are DataFusion 55.0.0's own, copied
//! out of the umbrella crate with its `crate::` imports pointed at the component crates and the
//! COPY arm refused. This test is the generator: it fails when the committed files differ from what
//! it would write, and `BURRMILL_REGENERATE=1 cargo test -p burrmill --features datafusion --test
//! generated_planner` writes them instead. It replaces the footprint6 probe's script, which wrote
//! into the probe's own tree.

use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

const UPSTREAM: &str = "datafusion-55.0.0";
const HEADER: &str = "// Generated by crates/burrmill/tests/generated_planner.rs from datafusion-55.0.0. Do not edit.\n";

const IMPORT_REWRITES: &[(&str, &str)] = &[
    (
        "use crate::datasource::file_format::file_type_to_format;\n",
        "",
    ),
    ("use crate::datasource::listing::ListingTableUrl;\n", ""),
    (
        "use crate::datasource::physical_plan::{FileOutputMode, FileSinkConfig};\n",
        "",
    ),
    (
        "use crate::datasource::{DefaultTableSource, source_as_provider};\n",
        "use datafusion_catalog::default_table_source::{DefaultTableSource, source_as_provider};\n",
    ),
    (
        "use crate::error::{DataFusionError, Result};\n",
        "use datafusion_common::{DataFusionError, Result};\n",
    ),
    (
        "use crate::execution::context::ExecutionProps;\n",
        "use datafusion_expr::execution_props::ExecutionProps;\n",
    ),
    (
        "use crate::logical_expr::utils::generate_sort_key;\n",
        "use datafusion_expr::utils::generate_sort_key;\n",
    ),
    ("use crate::logical_expr::", "use datafusion_expr::"),
    (
        "use crate::physical_expr::",
        "use datafusion_physical_expr::",
    ),
    (
        "use crate::physical_plan::",
        "use datafusion_physical_plan::",
    ),
    (
        "use crate::schema_equivalence::schema_satisfied_by;\n",
        "use super::schema_equivalence::schema_satisfied_by;\n",
    ),
];

/// The umbrella crate's source, wherever cargo unpacked it. It is in the lockfile through the bench.
fn upstream_src() -> PathBuf {
    let cargo = std::env::var("CARGO").unwrap_or_else(|_| "cargo".into());
    let out = Command::new(cargo)
        .args(["metadata", "--locked", "--format-version", "1"])
        .current_dir(env!("CARGO_MANIFEST_DIR"))
        .output()
        .expect("cargo metadata");
    assert!(
        out.status.success(),
        "cargo metadata: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    let json = String::from_utf8(out.stdout).expect("utf-8 metadata");
    let tail = format!("{UPSTREAM}/Cargo.toml\"");
    let end = json
        .find(&tail)
        .unwrap_or_else(|| panic!("{UPSTREAM} is not in the workspace's metadata"));
    let start = json[..end].rfind('"').expect("opening quote") + 1;
    Path::new(&json[start..end + UPSTREAM.len()]).join("src")
}

fn until_tests(path: &Path) -> String {
    let text = std::fs::read_to_string(path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
    let mut out = String::new();
    for line in text.split_inclusive('\n') {
        if line.starts_with("#[cfg(test)]") {
            break;
        }
        out.push_str(line);
    }
    out
}

/// The COPY arm is the only one that needs the umbrella's file-sink helpers.
fn refuse_copy(text: &str) -> String {
    let start = text
        .find("            LogicalPlan::Copy(CopyTo {")
        .expect("Copy arm");
    let next = start
        + text[start..]
            .find("            LogicalPlan::Dml(DmlStatement {")
            .expect("Dml arm after Copy");
    let stub = "            LogicalPlan::Copy(_) => {\n                return not_impl_err!(\"COPY is not part of the admitted subset\");\n            }\n";
    format!("{}{stub}{}", &text[..start], &text[next..])
}

fn planner(src: &Path) -> String {
    let mut text = refuse_copy(&until_tests(&src.join("physical_planner.rs")));
    for (old, new) in IMPORT_REWRITES {
        text = text.replace(old, new);
    }
    let leftover: Vec<&str> = text
        .lines()
        .filter(|l| {
            l.contains("crate::")
                && !l.contains("schema_equivalence")
                && !l.contains("config::ExecutionOptions")
        })
        .collect();
    assert!(leftover.is_empty(), "unrewritten imports: {leftover:#?}");
    format!("{HEADER}#![allow(unused_imports, dead_code, unused_variables, clippy::all)]\n{text}")
}

fn schema_equivalence(src: &Path) -> String {
    let text = until_tests(&src.join("schema_equivalence.rs")).replace(
        "pub(crate) fn schema_satisfied_by",
        "pub fn schema_satisfied_by",
    );
    format!("{HEADER}{text}")
}

/// As `cargo fmt` leaves the committed file.
fn rustfmt(text: &str) -> String {
    let mut child = Command::new(std::env::var("RUSTFMT").unwrap_or_else(|_| "rustfmt".into()))
        .args(["--edition", "2024", "--emit", "stdout"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("rustfmt; the toolchain's rustfmt component must be installed");
    std::io::Write::write_all(child.stdin.as_mut().unwrap(), text.as_bytes()).unwrap();
    let out = child.wait_with_output().unwrap();
    assert!(
        out.status.success(),
        "rustfmt: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    String::from_utf8(out.stdout).unwrap()
}

#[test]
fn committed_planner_is_what_the_generator_writes() {
    let src = upstream_src();
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("src/df/generated");
    let regenerate = std::env::var_os("BURRMILL_REGENERATE").is_some();
    for (name, text) in [
        ("physical_planner.rs", planner(&src)),
        ("schema_equivalence.rs", schema_equivalence(&src)),
    ] {
        let want = rustfmt(&text);
        let path = dir.join(name);
        if regenerate {
            std::fs::write(&path, &want).unwrap();
            continue;
        }
        let have = std::fs::read_to_string(&path).unwrap();
        if have != want {
            let at = have
                .lines()
                .zip(want.lines())
                .position(|(a, b)| a != b)
                .unwrap_or(have.lines().count().min(want.lines().count()));
            panic!(
                "{name} differs from the generator's output at line {}:\n  committed: {:?}\n  generated: {:?}\nregenerate with BURRMILL_REGENERATE=1",
                at + 1,
                have.lines().nth(at),
                want.lines().nth(at),
            );
        }
    }
}
